# Generated by Django 4.0.6 on 2023-06-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('text', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('price', models.IntegerField(default=100000, verbose_name='قیمت')),
                ('time', models.IntegerField(default=2, verbose_name='زمان آماده شدن غذا')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('image', models.ImageField(upload_to='webs/', verbose_name='تصویر غذا')),
                ('type', models.CharField(choices=[('iranianfood', 'غذای ایرانی'), ('fastfood', 'فست فود'), ('juices', 'نوشیدنی')], default='fastfood', max_length=50, verbose_name='نوع غذا')),
            ],
        ),
    ]
